"""
Database Models
"""
from sqlalchemy import Column, String, Integer, Text, DateTime, Float, ARRAY, JSON
from sqlalchemy.dialects.postgresql import UUID
from datetime import datetime
import uuid
from app.database import Base


class Document(Base):
    """Source documents for RAG"""
    __tablename__ = "documents"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String(500), nullable=False)
    document_type = Column(String(50), nullable=False)
    category = Column(String(50))
    content_text = Column(Text, nullable=False)
    file_path = Column(String(1000))
    file_format = Column(String(10))
    created_date = Column(DateTime)
    uploaded_date = Column(DateTime, default=datetime.utcnow)
    author = Column(String(200))
    department = Column(String(100))
    word_count = Column(Integer)
    page_count = Column(Integer)
    success_rating = Column(Float)
    usage_count = Column(Integer, default=0)
    doc_metadata = Column(JSON)





class GeneratedDocument(Base):
    """Documents generated by the system"""
    __tablename__ = "generated_documents"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True))
    request_text = Column(Text, nullable=False)
    document_type = Column(String(50))
    generated_content = Column(Text)
    source_documents = Column(ARRAY(UUID(as_uuid=True)))  # Array of source document IDs
    output_format = Column(String(10))
    file_path = Column(String(1000))
    status = Column(String(20), default="pending")  # pending, completed, failed
    created_at = Column(DateTime, default=datetime.utcnow)
    generation_time_ms = Column(Integer)
    
    # Additional metadata
    title = Column(String(500))
    tone = Column(String(50))
    length = Column(String(50))
